stages:
   - build

docker-build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - docker login -u serpensin -p $DOCKER_PW
    - docker buildx create --use
    - sleep 2
    - export DOCKER_CLI_EXPERIMENTAL=enabled
    - docker buildx build --build-arg BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ") --build-arg VERSION=${CI_COMMIT_TAG} --compress --no-cache --platform linux/386 -t docker.bloodygang.com/serpensin/autopublisher:latest-linux-386 --push .
    - docker buildx build --build-arg BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ") --build-arg VERSION=${CI_COMMIT_TAG} --compress --no-cache --platform linux/amd64 -t docker.bloodygang.com/serpensin/autopublisher:latest-linux-amd64 --push .
    - docker buildx build --build-arg BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ") --build-arg VERSION=${CI_COMMIT_TAG} --compress --no-cache --platform linux/arm/v6 -t docker.bloodygang.com/serpensin/autopublisher:latest-linux-arm-v6 --push .
    - docker buildx build --build-arg BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ") --build-arg VERSION=${CI_COMMIT_TAG} --compress --no-cache --platform linux/arm/v7 -t docker.bloodygang.com/serpensin/autopublisher:latest-linux-arm-v7 --push .
    - docker buildx build --build-arg BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ") --build-arg VERSION=${CI_COMMIT_TAG} --compress --no-cache --platform linux/arm64/v8 -t docker.bloodygang.com/serpensin/autopublisher:latest-linux-arm64-v8 --push .
    - docker buildx build --build-arg BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ") --build-arg VERSION=${CI_COMMIT_TAG} --compress --no-cache --platform linux/ppc64le -t docker.bloodygang.com/serpensin/autopublisher:latest-linux-ppc64le --push .
    - docker buildx build --build-arg BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ") --build-arg VERSION=${CI_COMMIT_TAG} --compress --no-cache --platform linux/s390x -t docker.bloodygang.com/serpensin/autopublisher:latest-linux-s390x --push .
    - docker manifest annotate docker.bloodygang.com/serpensin/autopublisher:latest docker.bloodygang.com/serpensin/autopublisher:latest-linux-386 --os linux --arch 386
    - docker manifest annotate docker.bloodygang.com/serpensin/autopublisher:latest docker.bloodygang.com/serpensin/autopublisher:latest-linux-amd64 --os linux --arch amd64
    - docker manifest annotate docker.bloodygang.com/serpensin/autopublisher:latest docker.bloodygang.com/serpensin/autopublisher:latest-linux-arm-v6 --os linux --arch arm --variant v6
    - docker manifest annotate docker.bloodygang.com/serpensin/autopublisher:latest docker.bloodygang.com/serpensin/autopublisher:latest-linux-arm-v7 --os linux --arch arm --variant v7
    - docker manifest annotate docker.bloodygang.com/serpensin/autopublisher:latest docker.bloodygang.com/serpensin/autopublisher:latest-linux-arm64-v8 --os linux --arch arm64 --variant v8
    - docker manifest annotate docker.bloodygang.com/serpensin/autopublisher:latest docker.bloodygang.com/serpensin/autopublisher:latest-linux-ppc64le --os linux --arch ppc64le
    - docker manifest annotate docker.bloodygang.com/serpensin/autopublisher:latest docker.bloodygang.com/serpensin/autopublisher:latest-linux-s390x --os linux --arch s390x
    - docker manifest push docker.bloodygang.com/serpensin/autopublisher:latest
  timeout: 45m

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      when: always
    - if: $CI_PIPELINE_SOURCE == "trigger"
      when: always

