stages:
   - build

docker-build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - export DOCKER_CLI_EXPERIMENTAL=enabled
    - docker login docker.bloodygang.com -u serpensin -p $DOCKER_PW
    - docker buildx create --use
    - sleep 2
    - docker build --build-arg BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ") --build-arg VERSION=${CI_COMMIT_TAG} -t docker.bloodygang.com/serpensin/autopublisher .

  timeout: 10m

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      when: always
    - if: $CI_PIPELINE_SOURCE == "trigger"
      when: always

