stages:
   - build

docker-build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - export DOCKER_CLI_EXPERIMENTAL=enabled
    - docker login docker.bloodygang.com -u serpensin -p $DOCKER_PW
    - docker buildx create --use
    - sleep 2
    - docker buildx build --build-arg BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ") --build-arg VERSION=${CI_COMMIT_TAG} --compress --no-cache --platform linux/amd64 -t docker.bloodygang.com/serpensin/autopublisher:latest-linux-amd64 --push .
    - docker manifest annotate docker.bloodygang.com/serpensin/autopublisher:latest docker.bloodygang.com/serpensin/autopublisher:latest-linux-amd64 --os linux --arch amd64
    - docker manifest push docker.bloodygang.com/serpensin/autopublisher:latest
  timeout: 10m

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      when: always
    - if: $CI_PIPELINE_SOURCE == "trigger"
      when: always

